# -*- coding: utf-8 -*-
"""задание 1.2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W7kmhLXlCrHmgcaTdh24ec1JaBoJm9ei

Изучить список открытых API (https://www.programmableweb.com/category/all/apis). Найти среди них любое, требующее авторизацию (любого типа). Выполнить запросы к нему, пройдя авторизацию. Ответ сервера записать в файл.
Если нет желания заморачиваться с поиском, возьмите API вконтакте (https://vk.com/dev/first_guide). Сделайте запрос, чтобы получить список всех сообществ на которые вы подписаны.
"""

import requests
import json

#https://oauth.vk.com/blank.html#access_token=9a1619b10583b05dbc56b44174766387057a1ef86ca36b9a14391f**********5f242b9025bd06da4&expires_in=0&user_id=53237253&email=Kalina7@yandex.ru
#https://api.vk.com/method/METHOD_NAME?PARAMETERS&access_token=ACCESS_TOKEN&v=V

ACCESS_TOKEN = 9a1619b10583b05dbc56b44174766387057a1ef86ca36b9a1********



method = 'groups.get'
token = '9a1619b10583b05dbc56b44174766387057a1ef86ca36b9a14391f5a4c56d5dea0b65f242b9025bd06da4'
version = 5.78

params = {
    'user_id':'120159853',
    'access_token':'token'}

url = 'https://api.vk.com/method/{method}?{params}&access_token={token}&v=5.78'



response = requests.get(url)

response.json()